language: node_js

node_js:
  - "10"

sudo: false

cache:
  directories:
    - node_modules

notifications:
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

before_install:
  - npm install -g npm@6
  - npm install -g grunt-cli

install:
  - travis_retry npm install --silent
  - npm ls --depth 0 | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g'
  - grunt lint

# now run the tests!
script:
  - npm test
